package:
    name: gtsam
    version: 3.2.1

source:
    fn: gtsam-3.2.1.zip
    url: https://research.cc.gatech.edu/borg/sites/edu.borg/files/downloads/gtsam-3.2.1.zip
  
build:
    number: 0

requirements:
    build:
        - cmake
    run:
        - cmake

about:
    home: https://bitbucket.org/gtborg/gtsam
    license: BSD
