package:
    name: pygtsam
    version: 3.2.1

source:
  path: pygtsam
  
build:
    number: 0

requirements:
    build:
      - python
      - cmake
      - numpy
      
    run:
      - python
      - numpy
      
about:
    home: https://collab.cc.gatech.edu/borg/gtsam/
    license: BSD
    summary: Georgia Tech Smoothing and Mapping library (Python)
